name_target: "MARS"

telescope: 'SRT'
pixel_size: 3 #arcsec
num_ch_map: 100 #numero di canali con cui fare la mappa. Se si vogliono tutti i pixel, scrivere 'all'

#range_ty: [3,2,1,0,-1,-2,-3]

paths: #NB: NON METTERE SLASH FINALE SUL PATH!!!!!!!
  # Location of TOD files
  tods: "/Users/eleonora/Desktop/SRT-marzo/20250404-181903-MISTRAL-YOFFSET_MARS_TZ-2"
  #File of the channels' responsivity
  resp: False #'/home/eleobar/MISTRAL_gen+map-maker/optical_responsivity_new_lowSNR_200mK.pkl'
  #File of the channels' offsets
  offset_pixel: '/Users/eleonora/Desktop/mistral/mirtos_multiprocess/chp_offset_rel8_31MAR25_matteo.dat'
  #File of the GAIN-CAL or of Skydip + parameters for calibration
  skydip: False #'/Users/eleonora/Desktop/MATRIX_cartelle/20250224-001119-MISTRAL-GAIN_CAL/20250224-001119-MISTRAL-GAIN_CAL_008_001.fits'
  tau: 0.16
  T_atm: 267

flag_track: True

binner:
  projection: 'SIN' #'SIN' oppure 'GNOM'
  frame: 'AZEL' # 'AZEL' oppure 'RADEC'

filtering:
  #info of box around source to mask during baseline removal and filtering
  radius: 0 #arcsec
  baseline_rem: 'cutted'
  #If True, the detrended TODs are filtered, or else the raw TODs
  use_detrend_tods: True
  #If True, the filtering is done only computing the generale commone mode
  gen_cm: False
  plot_cm: False
  #If True, the filtering is done computing the custom commone mode for each pixel
  cust_cm: True
  plot_corr_matrix: False
  plt_cust_cm: False

unfilt_map: 'dt' #'raw'=TODs raw are used or 'dt'=TODs detrended are used

plot_maps:
  plot_filt: True
  plot_unfilt: False
  plot_counts: False
  plot_std: False

#Save resulting maps in file fits
save_maps: True
path_saved_maps: 0 #if 0, maps are saved in [paths][tods]_maps
save_single_pixel_maps: False 
